# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2019'

variables:
    CN_SENCHA_EXT_VERSION: '6.2.0'
    CN_SENCHA_CMD_VERSION: '6.5.3.6'

steps:
- task: CacheBeta@1
  inputs:
    key: extjs
    restoreKeys: extjs
    path: $(Pipeline.Workspace)/ext-$(CN_SENCHA_EXT_VERSION)-gpl.zip
    cacheHitVar: CACHE_RESTORED
- powershell: Invoke-WebRequest "http://cdn.sencha.com/ext/gpl/ext-$($env:CN_SENCHA_EXT_VERSION)-gpl.zip" -OutFile "ext-$($env:CN_SENCHA_EXT_VERSION)-gpl.zip"
  condition: ne(variables.CACHE_RESTORED, 'true')
- task: ExtractFiles@1
  inputs:
    archiveFilePatterns: "$(Pipeline.Workspace)/ext-$(CN_SENCHA_EXT_VERSION)-gpl.zip"
    destinationFolder: .

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
